export const DEFAULT_VIEWPORT_MATRIX_TARGET =
  '/tests/responsive-layout-matrix.html?capture=1';

export const VIEWPORT_PRESETS = Object.freeze([
  {
    id: 'desktop',
    label: 'Desktop',
    device: 'Laptop',
    group: 'desktop',
    width: 1440,
    height: 900,
    orientation: 'landscape',
    hasTouch: false,
    isMobile: false,
  },
  {
    id: 'desktop-wide',
    label: 'Desktop wide',
    device: 'Full HD display',
    group: 'desktop',
    width: 1920,
    height: 1080,
    orientation: 'landscape',
    hasTouch: false,
    isMobile: false,
  },
  {
    id: 'phone-compact-portrait',
    label: 'Compact phone',
    device: 'iPhone SE class',
    group: 'phone',
    width: 375,
    height: 667,
    orientation: 'portrait',
    hasTouch: true,
    isMobile: true,
  },
  {
    id: 'phone-compact-landscape',
    label: 'Compact phone landscape',
    device: 'iPhone SE class',
    group: 'phone',
    width: 667,
    height: 375,
    orientation: 'landscape',
    hasTouch: true,
    isMobile: true,
  },
  {
    id: 'phone-modern-portrait',
    label: 'Modern phone',
    device: 'iPhone 12–14 class',
    group: 'phone',
    width: 390,
    height: 844,
    orientation: 'portrait',
    hasTouch: true,
    isMobile: true,
  },
  {
    id: 'phone-modern-landscape',
    label: 'Modern phone landscape',
    device: 'iPhone 12–14 class',
    group: 'phone',
    width: 844,
    height: 390,
    orientation: 'landscape',
    hasTouch: true,
    isMobile: true,
  },
  {
    id: 'tablet-standard-portrait',
    label: 'Standard tablet',
    device: 'iPad class',
    group: 'tablet',
    width: 768,
    height: 1024,
    orientation: 'portrait',
    hasTouch: true,
    isMobile: true,
  },
  {
    id: 'tablet-standard-landscape',
    label: 'Standard tablet landscape',
    device: 'iPad class',
    group: 'tablet',
    width: 1024,
    height: 768,
    orientation: 'landscape',
    hasTouch: true,
    isMobile: true,
  },
  {
    id: 'tablet-large-portrait',
    label: 'Large tablet',
    device: 'iPad Air class',
    group: 'tablet',
    width: 820,
    height: 1180,
    orientation: 'portrait',
    hasTouch: true,
    isMobile: true,
  },
  {
    id: 'tablet-large-landscape',
    label: 'Large tablet landscape',
    device: 'iPad Air class',
    group: 'tablet',
    width: 1180,
    height: 820,
    orientation: 'landscape',
    hasTouch: true,
    isMobile: true,
  },
]);

export const VIEWPORT_GROUPS = Object.freeze([
  { id: 'desktop', label: 'Desktop' },
  { id: 'phone', label: 'Phone' },
  { id: 'tablet', label: 'Tablet' },
]);
